apiVersion: v1
kind: Service
metadata:
  name: pethub-service-np
  labels:
    name: pethub-deployment
    app: pethub-app
spec:
  type: NodePort
  selector:
    app: pethub-app  # Pods with this label is exposed
  ports:
    - protocol: TCP
      port: 3000  # The port where your pethub app listens inside the container.
      nodePort: 30072
